add init script

diff --git a/bin/mapreduce b/bin/mapreduce
--- a/bin/mapreduce
+++ b/bin/mapreduce
@@ -4,8 +4,16 @@ set -Eeuo pipefail
 
 if [ $1 -eq "start" ]
 then
-pgrep -f mapreduce-manager  # check if you already started it
-pgrep -f mapreduce-worker  # check if you already started it
+if pgrep -f mapreduce-manager &> /dev/null
+then
+  echo "Error: mapreduce-manager is already running"
+  exit 1
+fi
+if pgrep -f mapreduce-worker &> /dev/null
+then
+  echo "Error: mapreduce-worker is already running"
+  exit 1
+fi
 
 # Exit 1 if a Manager or Worker is already running. Otherwise, execute the following commands.
 echo "starting mapreduce ..."
@@ -35,17 +43,37 @@ set -o pipefail
 
 echo '{"message_type": "shutdown"}' | $NC localhost 6000 || true
 sleep 2  # give the Manager time to receive signal and send to Workers
+
+if pgrep -f mapreduce-manager &> /dev/null; then
+  echo "killing mapreduce manager ..."
+  pkill -f mapreduce-manager || true
+fi
+if pgrep -f mapreduce-worker &> /dev/null; then
+  echo "killing mapreduce worker ..."
+  pkill -f mapreduce-worker || true
+fi
+
 fi
 
 
 if [ $1 -eq "status" ]
 then
   # Print whether or not the Manager is running,
-  
+  if pgrep -f mapreduce-manager &> /dev/null; then
+    echo "manager running"
+    if pgrep -f mapreduce-worker &> /dev/null; then
+      echo "worker running"
+      exit 0
+    fi
+  fi
+  echo "manager not running"
+  echo "workers not running"
+  exit 1
 fi
 
 if [ $1 -eq "restart" ]
 then
   # Restart the program
-  
+  ./bin/mapreduce stop
+  ./bin/mapreduce start
 fi
